all:
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3

  children:
    web:
      hosts:
        web-1:
          ansible_host: diploma-web-1
        web-2:
          ansible_host: diploma-web-2

    monitoring:
      hosts:
        prometheus:
          ansible_host: diploma-prometheus
        grafana:
          ansible_host: diploma-grafana

    logging:
      hosts:
        elasticsearch:
          ansible_host: diploma-elasticsearch
        kibana:
          ansible_host: diploma-kibana
          