---
- name: Apply common configuration
  hosts: all
  become: true
  gather_facts: true

  roles:
    - common

- name: Configure web servers
  hosts: web
  become: true
  gather_facts: true

  roles:
    - nginx_site
